FROM node:12-slim

ENV TZ Asia/Seoul

ENV APP /app
RUN mkdir -p APP
COPY . APP
WORKDIR APP

# Build
RUN npm install
ENV NODE_ENV production
RUN npm run build:production

EXPOSE 80
# Command
CMD ["npm", "run", "start:production"]